[build]
  functions = "netlify/functions"
  publish = "public"
  command = "pip install -r requirements.txt"

[dev]
  command = "echo 'Dev server not supported for Netlify Functions'"

[functions]
  node_bundler = "esbuild"